apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoline-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoline-api
  template:
    metadata:
      labels:
        app: infoline-api
    spec:
      containers:
        - name: infoline-api
          image: pbou49/infoline-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: infoline-api-service
spec:
  type: LoadBalancer
  selector:
    app: infoline-api
  ports:
    - port: 80
      targetPort: 8080
