apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::745208956194:user/eks-admin
      username: eks-admin
      groups:
        - system:masters
